### ISSUE TITLE
Running randomprovincemain.py opens cmd box then promptly vanishes, doing nothing.

### ISSUE THREAD

**Issue by Bloodman123726** [ThatsJustBonkers/RandomRGOVictoria2#2]
Hello, I downloaded this and placed the correct directory for the provinces as specified but still it does not work. Done outside the Victoria 2 folder as it said to do as well

**Comment by Eake123** [comment]
can you try running it in an IDE like visual studio code and see if it reports an error? After doing this paste the error here, or if no error mention that.

**Comment by Eake123** [comment]
I ran the code and I realized I was calling a function in the random class that I didn't mean to add into the commit. I just updated the randomclass.py file so try redownloading it

**Comment by Bloodman123726** [comment]
Hey, thanks for the quick reply. I tested out the new randomclass.py and it is working flawlessly now. Thank you!
